#! /bin/zsh

if ((# == 0)) then
    FILENAME=personal_$(date +%Y-%m-%d).tar.gz
    rm -f $FILENAME
    tar -zcv --exclude '.DS_Store' -f $FILENAME -C ~/Documents/ personal/
    gpg --no-symkey-cache --cipher-algo AES256 -c $FILENAME
    rm -f $FILENAME
else
    FILENAME=$1
    gpg --no-symkey-cache --cipher-algo AES256 $FILENAME
    tar -xf ${FILENAME%.*}
    rm -f ${FILENAME%.*}
fi
