#! /bin/bash

EXCLUDE="$PWD/build"

rm -f cscope.out

find "$PWD" -name '*.[ch]' \
-o -name '*.cc' \
-o -name '*.hh' \
-o -name '*.cpp' \
-o -name '*.hpp' \
-o -name '*.cxx' \
-o -name '*.hxx' | grep -v $EXCLUDE > cscope.files

cscope -b -i cscope.files

rm -f cscope.files
