#! /bin/bash

find "$PWD" -name '*.[ch]' \
-o -name '*.cc' \
-o -name '*.hh' \
-o -name '*.cpp' \
-o -name '*.hpp' \
-o -name '*.cxx' \
-o -name '*.hxx' > cscope.files

cscope -b -i cscope.files

rm -f cscope.files
