#! /bin/sh

if [ -n "$(uname -a | grep -i ubuntu)" ]; then
    sudo apt-get update
    sudo apt-get install vim git htop tree cscope gnupg -y
elif [ -n "$(uname -a | grep -i darwin)" ]; then
	brew install htop tree cscope gnupg
elif [ -n "$(uname -a | grep "GNU/Linux")" ]; then
    sudo pacman -S vim git htop tree cscope gnupg
else
	echo 'Sorry, cannot install packages on this machine.'
fi

# Blast away old user config
rm -rf ~/.vimrc ~/.bash_aliases ~/.vim

# Add user config 
ln -sf $(pwd)/.vimrc ~/.vimrc
ln -sf $(pwd)/.bash_aliases ~/.bash_aliases
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
