#! /bin/bash

PACKAGES="vim tmux htop tree cscope gnupg curl"

if [ -n "$(uname -a | grep -i ubuntu)" ]; then
    sudo apt-get update
    sudo apt-get install $PACKAGES -y
elif [ -n "$(uname -a | grep -i darwin)" ]; then
    brew install $PACKAGES
elif [ -n "$(uname -a | grep "GNU/Linux")" ]; then
    sudo pacman -S $PACKAGES
else
    echo 'Cannot install packages on this machine.'
fi

# Blast away old user config
rm -rf ~/.vimrc ~/.aliases ~/.zshrc.user ~/.tmux.conf ~/.vim

# Add user config
ln -sf $(pwd)/.vimrc ~/.vimrc
ln -sf $(pwd)/.aliases ~/.aliases
ln -sf $(pwd)/.zshrc.user ~/.zshrc.user
ln -sf $(pwd)/.tmux.conf ~/.tmux.conf
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
