#! /bin/bash

PACKAGES="cscope curl gnupg htop ripgrep tmux tree vim"

# Install packages
if [[ $* == *--skip* ]]; then
    echo "Skipping package install."
else
    if [ -n "$(uname -a | grep -i ubuntu)" ]; then
        sudo apt-get update
        sudo apt-get install $PACKAGES -y
    elif [ -n "$(uname -a | grep -i darwin)" ]; then
        brew install $PACKAGES
    elif [ -n "$(uname -a | grep "GNU/Linux")" ]; then
        sudo pacman -S $PACKAGES
    else
        echo "Cannot install packages on this machine."
    fi
fi

DOTFILES=".bash_aliases .p10k.zsh .tmux.conf .vimrc .zshenv"

# Add dotfiles
for filename in $DOTFILES; do
    rm -f $HOME/$filename
    ln -sf $(pwd)/$filename $HOME/$filename
done

# Install vim-plug
rm -rf $HOME/.vim
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim > /dev/null 2>&1

# Install powerlevel10k
rm -rf $HOME/.powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.powerlevel10k

echo "Setup complete."
