#! /bin/bash

DOTFILES=".bash_aliases .p10k.zsh .tmux.conf .vimrc .zshenv"

# Remove dotfiles
for filename in $DOTFILES; do
    rm -f $HOME/$filename
done

# Remove vim-plug
rm -rf $HOME/.vim

# Remove powerlevel10k
rm -rf $HOME/.powerlevel10k

echo "Teardown complete."
