#! /bin/bash

DOTFILES=".vimrc .bash_aliases .zshrc.user .tmux.conf .p10k.zsh"

# Remove dotfiles
for filename in $DOTFILES; do
    rm -f $HOME/$filename
done

# Remove duplicate symlink for zshenv
rm -f $HOME/.zshenv

# Remove vim-plug
rm -rf $HOME/.vim

# Remove powerlevel10k
rm -rf $HOME/.powerlevel10k

echo "Teardown complete."
