#! /bin/bash

DOTFILES=".bash_aliases .tmux.conf .vimrc .zshrc"

# Remove dotfiles
for filename in $DOTFILES; do
    rm -f $HOME/$filename
done

# Remove vim-plug
rm -rf $HOME/.vim

echo "Teardown complete."
